### ISSUE TITLE
Where to find the "data_lidc.hdf5"?

### ISSUE THREAD

**Issue by saraao** [LarsDoorenbos/ccdm-stochastic-segmentation#1]
Hi, thank you for sharing your code and great work! Just wonder where can we download the file "data_lidc.hdf5", only find the "data_lidc.pickle" but not .hdf5 on [Stefan Knegt's gihub page](https://github.com/stefanknegt/Probabilistic-Unet-Pytorch). Is there and way we can convert the .pickle to .hdf5? Thank you!

**Comment by LarsDoorenbos** [comment]
Thank you for your interest in our work.

The LIDCv2 data can now be found [here](https://console.cloud.google.com/storage/browser/hpunet-data/lidc_crops;tab=objects?prefix=&forceOnObjectsSortingFiltering=false) (from the [Hierarchical Probabilistic U-Net
](https://github.com/deepmind/deepmind-research/tree/master/hierarchical_probabilistic_unet) repo), see also [this issue](https://github.com/SimonKohl/probabilistic_unet/issues/14). Apparently, it is no longer a .hdf5 file, so you would have to adapt the dataloading slightly, similar to that in lidc_orig.py.

**Comment by saraao** [comment]
Thank you for getting back to me so fast!

**Comment by ZhouCX117** [comment]
Hi, thanks for your excellent work. Could you please share the processed "data_lidc.hdf5"? Thanks a lot!

**Comment by ZhouCX117** [comment]
@LarsDoorenbos By the way, where can I find the derivation process？ Looking forward to your answer~

**Comment by LarsDoorenbos** [comment]
We now uploaded the .hdf5 file to [here](https://drive.google.com/drive/folders/13KWz8GS5Agrg8vg-N2CLa_ltEWGRWvWd?usp=sharing). 

For your second question, which derivation process do you mean?

**Comment by ZhouCX117** [comment]
Hi, thanks for your reply @LarsDoorenbos . I want to know the derivation process for eq.7.

**Comment by LarsDoorenbos** [comment]
The categorical diffusion formulation comes from [this paper](https://proceedings.neurips.cc/paper/2021/file/67d96d458abdef21792e6d8e590244e7-Paper.pdf), and our eqs. 6 & 7 come from eq. 13 there.

**Comment by ZhouCX117** [comment]
Thanks for your quick reply! Have a good day!

**Comment by ZhouCX117** [comment]
@LarsDoorenbos Hi, it is me again. When I train on my dataset, the result is not nice. So could you please release your trained model? Thanks a lot!

**Comment by LarsDoorenbos** [comment]
I put one of our models from LIDCv1 along with the parameter file needed for evaluating GED16 [here](https://drive.google.com/drive/folders/1pcXOZpQlSLJOOhId6yZa_3vYS-L0nA4S?usp=sharing)
