### ISSUE TITLE
ImportError: cannot import name '_build_cond_encoder' from 'ddpm.trainer'

### ISSUE THREAD

**Issue by saraao** [LarsDoorenbos/ccdm-stochastic-segmentation#2]
Hi, thanks for sharing your great work again. 

When I run the evaluation, it shows:
    File ".../ccdm-stochastic-segmentation/evaluation/eval_cdm.py", line 30, in <module>
    from ddpm.trainer import _build_model, _build_cond_encoder, _build_feature_cond_encoder
    ImportError: cannot import name '_build_cond_encoder' from 'ddpm.trainer'". (.../ccdm-stochastic-segmentation/ddpm/trainer.py)

Just wondering where to find the "_build_cond_encoder" function. Look like it's not in ddpm/trainer.py now. Thank you!

**Comment by LarsDoorenbos** [comment]
Hey, I updated the code to remove the unused cond_encoder from eval_cdm.py. I believe it should work now, but let me know if you run into any more issues!
