### ISSUE TITLE
Trained models for Cityscapes segmentation

### ISSUE THREAD

**Issue by Siddharth-Shrivastava7** [LarsDoorenbos/ccdm-stochastic-segmentation#3]
Hi @LarsDoorenbos , 

I really like your work.   

It would be very helpful, if you can upload the link of trained U-Net models on cityscapes dataset. 

Thanks!

**Comment by LarsDoorenbos** [comment]
Thank you for your interest.

We will release the weights for the Cityscapes models in the coming weeks.

**Comment by Siddharth-Shrivastava7** [comment]
Ok, Thanks for your quick response! 

I will be waiting for it.

**Comment by Siddharth-Shrivastava7** [comment]
Hi @LarsDoorenbos , 

I have trained a CCDM-Dino model, and inferred the results on cityscapes validation dataset by fusing 10 samples for individual segmentation. I have a query, the results reported in the paper is 65.8 mIoU but, the model I trained has 62.8 mIoU (with the configurations mentioned in the paper). 

I request you to please upload the weights and configurations (if any additional) for reproducing results coherent to the paper. 

Hoping for your response, 
Thanks!

**Comment by TheoPis** [comment]
Hi @Siddharth-Shrivastava7 , we have pushed a new branch "cts" where you can find the code to train and evaluate models on cityscapes. We also have added a cdm_dino_256x512 checkpoint (see the releases). Please see "Cityscapes.md" in branch "cts" for instructions on how to run. 

Further, it is possible that if you used the code and params.yml from the "main" branch  to obtain the 62.8 mIoU you were not using dino, and that is possibly why you get close to our cdm without dino result of the paper. Please let us know if there are any other questions or problems with the code.

**Comment by Siddharth-Shrivastava7** [comment]
Alright, Thanks for your support!
I will check the code.
